name: Daily Commit

on:
  schedule:
    # Runs every day at 08:30 UTC
    - cron: "30 8 * * *"
  workflow_dispatch:

jobs:
  commit-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Daily Commit by 24f2002242@ds.study.iitm.ac.in
        run: |
          date >> daily_log.txt
          git config user.name "github-actions[bot]"
          git config user.email "24f2002242@ds.study.iitm.ac.in"
          git add daily_log.txt
          git commit -m "Automated daily commit $(date -u)"
          git push
